title:              Yerina Blog
email:              orina8262@gmail.com
description:        iOS Development Blog
author:             Yerina Oh
baseurl:            ""
url:                "https://yerinaoh.github.io"

# Social Profiles
twitter_username:   YerinaOh
github_username:    YerinaOh
facebook_username:  YerinaOh
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
